[package]
name = "rematch"
version = "0.1.0"
edition = "2021"

[features]

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
codespan = "0.11.1"
codespan-reporting = "0.11.1"
lalrpop-util = "0.19.6"
thiserror = "1.0.30"

[dev-dependencies]
static_init = "1.0.0"
